spring.application.name=biblioteca-api

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=7654321julio

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true